### Getting the Employee details
GET http://localhost:4004/EmployeeSRV/Employee HTTP/1.1

### Create Employee
POST http://localhost:4004/EmployeeSRV/Employee HTTP/1.1
Content-Type: application/json

    {
      "fName": "Chiranjivi",
      "lName": "Seshadri",
      "gender": "Male",
      "DOB": "1990-02-01",
      "contractStarted": "2012-03-11",
      "email": "ChiranjiviSeshadri1@abc.com",
      "phone": "8564543279"
    }